### ISSUE TITLE
Occasionally pytest fails with xsim failing to load xe file

### ISSUE THREAD

**Issue by xross** [xmos/lib_xud#230]
For example:

xsim: error: C59076: problem loading file: test_bulk_rx_basic/bin/xs3_600_5_1_1/test_bulk_rx_basic_xs3_600_5_1_1.xe: Header tag incorrect

I believe its only when running over multiple processes.

**Comment by xross** [comment]
@DaveAtkinsonXMOS any ideas?

**Comment by xross** [comment]
I also get this on occasion: 

xsim: error: C59076: problem loading file: test_bulk_rx_basic_badcrc32/bin/xs3_800_6_4_127/test_bulk_rx_basic_badcrc32_xs3_800_6_4_127.xe: Not enough space in the buffer to hold the data
Process Process-126:
Traceback (most recent call last):
  File "/Users/ross/.pyenv/versions/3.7.4/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/Users/ross/.pyenv/versions/3.7.4/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/ross/sandboxes/sb_xud_view/lib_xud/tests/Pyxsim/__init__.py", line 80, in do_run_pyxsim
    xsi.run()
  File "/Users/ross/sandboxes/sb_xud_view/lib_xud/tests/Pyxsim/pyxsim.py", line 295, in run
    XsiStatus.error_if_not_valid(status)
  File "/Users/ross/sandboxes/sb_xud_view/lib_xud/tests/Pyxsim/pyxsim.py", line 58, in error_if_not_valid
    raise type("XSI_ERROR_" + enum, (Exception,), {})
Pyxsim.pyxsim.XSI_ERROR_INVALID_INSTANCE

**Comment by xross** [comment]
And a different one: 

xsim: error: C57411: no executable elf sectors found in file: test_bulk_rx_basic_nodata/bin/xs3_800_6_2_1/test_bulk_rx_basic_nodata_xs3_800_6_2_1.xe
Process Process-208:
Traceback (most recent call last):
  File "/Users/ross/.pyenv/versions/3.7.4/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/Users/ross/.pyenv/versions/3.7.4/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/ross/sandboxes/sb_xud_view/lib_xud/tests/Pyxsim/__init__.py", line 80, in do_run_pyxsim
    xsi.run()
  File "/Users/ross/sandboxes/sb_xud_view/lib_xud/tests/Pyxsim/pyxsim.py", line 286, in run
    self.xe = Xe(self.xe_path)
  File "/Users/ross/sandboxes/sb_xud_view/lib_xud/tests/Pyxsim/xe.py", line 89, in __init__
    self._get_platform_info()
  File "/Users/ross/sandboxes/sb_xud_view/lib_xud/tests/Pyxsim/xe.py", line 18, in _get_platform_info
    xn = parse("%s/platform_def.xn" % self._tempdir)
  File "/Users/ross/.pyenv/versions/3.7.4/lib/python3.7/xml/dom/minidom.py", line 1958, in parse
    return expatbuilder.parse(file)
  File "/Users/ross/.pyenv/versions/3.7.4/lib/python3.7/xml/dom/expatbuilder.py", line 910, in parse
    with open(file, 'rb') as fp:
FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/g3/6w32pm617cv2_vdcn65wb7ww0000gn/T/tmp080z8ki9/platform_def.xn'

**Comment by xross** [comment]
It occurred to me that since we don't have different build configs for each set of test params, xcommon will use the same directory for temp files (.build..)

**Comment by DaveAtkinsonXMOS** [comment]
Hmm, and I get 
```
xsim: error: C59076: problem loading file: test_bulk_rx_basic_badcrc32/bin/xs3_600_0_1_0/test_bulk_rx_basic_badcrc32_xs3_600_0_1_0.xe: Header tag incorrect
Process Process-8:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/davea/sandboxes/lib_xud_develop/lib_xud/tests/Pyxsim/__init__.py", line 80, in do_run_pyxsim
    xsi.run()
  File "/home/davea/sandboxes/lib_xud_develop/lib_xud/tests/Pyxsim/pyxsim.py", line 295, in run
    XsiStatus.error_if_not_valid(status)
  File "/home/davea/sandboxes/lib_xud_develop/lib_xud/tests/Pyxsim/pyxsim.py", line 58, in error_if_not_valid
    raise type("XSI_ERROR_" + enum, (Exception,), {})
Pyxsim.pyxsim.XSI_ERROR_INVALID_INSTANCE
```
which is similar to the first error Ross reported. 

Interestingly, if I try and run the referenced binary in xsim, I have no problem. Could it be we're trying to run it before it's finished building?

**Comment by kevinyeungxmos** [comment]
I got the same problem

**Comment by kevinyeungxmos** [comment]
see pr #250
